//! Finds the native MongoDB engine and links it in.
//!
//! By default it downloads the library published for this target and verifies its checksum;
//! building the engine from the pinned submodule takes hours, so it happens only when asked
//! for. Nothing in this file decides what the library *contains* -- that is `build_native.rs`,
//! which is deliberately separate so a fix to the downloader does not invalidate every
//! library already published.

use std::env;
use std::fs;
use std::io::{ErrorKind, Read};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use sha2::{Digest, Sha256};

// Everything that decides what the native library contains.
include!("build_native.rs");
// @generated by scripts/write-prebuilt-manifest.
include!("prebuilt.rs");

const NATIVE_LIBRARY: &str = "libembedded_mongodb_native.so";

/// Paths whose contents decide what the published library contains, relative to the
/// workspace root. `mongo` is the submodule gitlink: `git rev-list` reports a gitlink move as
/// a change to this path, which is why no content hash is needed.
const ARTIFACT_PATHS: &[&str] = &[
    "patches",
    "embedded-mongodb-sys/native",
    "embedded-mongodb-sys/build_native.rs",
];

/// One published artifact. The asset name is recorded rather than derived, so that CI writes
/// down exactly what it uploaded and the name and the hash cannot drift apart.
struct Prebuilt {
    target: &'static str,
    asset: &'static str,
    sha256: &'static str,
    size: u64,
    /// Minimum host glibc, for `*-linux-gnu` targets. `None` elsewhere.
    glibc_min: Option<(u32, u32)>,
}

fn main() {
    let crate_root = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = crate_root
        .parent()
        .expect("embedded-mongodb-sys must be inside the workspace")
        .to_path_buf();
    let target = env::var("TARGET").expect("cargo sets TARGET for build scripts");
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let host = env::var("HOST").unwrap_or_default();

    for name in [
        "EMBEDDED_MONGODB_NATIVE_LIB_DIR",
        "EMBEDDED_MONGODB_BUILD_FROM_SOURCE",
        "EMBEDDED_MONGODB_CACHE_DIR",
        "EMBEDDED_MONGODB_BAZEL_JOBS",
        "CARGO_NET_OFFLINE",
        "BAZEL",
        "CC",
        "CXX",
    ] {
        println!("cargo:rerun-if-env-changed={name}");
    }

    // Watched on every resolution path, and as directories: a per-file list misses a newly
    // added patch or header. Without these the staleness check below is unreachable for the
    // two edits developers actually make, and the next unrelated rebuild would compile
    // cpp/bridge.cc against a new native/embedded_mongodb_native.h while linking the engine
    // built from the old one. The five extern "C" names would still match.
    println!("cargo:rerun-if-changed=native");
    println!("cargo:rerun-if-changed=include");
    println!("cargo:rerun-if-changed=src/ffi.rs");
    println!("cargo:rerun-if-changed=cpp/bridge.cc");
    println!("cargo:rerun-if-changed=prebuilt.rs");
    println!("cargo:rerun-if-changed=build_native.rs");
    let patches = workspace_root.join("patches");
    if patches.is_dir() {
        println!("cargo:rerun-if-changed={}", patches.display());
    }

    let native_library = resolve(&workspace_root, &crate_root, &target);
    assert!(
        native_library.is_file(),
        "native library not found at {}",
        native_library.display()
    );
    let native_library = native_library
        .canonicalize()
        .expect("failed to resolve native library path");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    install(
        &native_library,
        &out_dir.join(NATIVE_LIBRARY),
        &target_os,
        &host,
    );

    // Half of the C++ runtime story; the native library covers the other half through its
    // own link flags. Without this the cxx bridge puts a `NEEDED libstdc++.so.6` on every
    // artifact that links it -- the Python extension module included -- which pins the
    // wheel's GLIBCXX floor to whichever toolchain happened to build it.
    let static_libstdcxx = (target_os == "linux"
        && env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("gnu"))
    .then(static_libstdcxx_dir)
    .flatten();
    let mut bridge = cxx_build::bridge("src/ffi.rs");
    bridge
        .file("cpp/bridge.cc")
        .include("include")
        .include("native")
        .std("c++20");
    if static_libstdcxx.is_some() {
        bridge.cpp_link_stdlib(None);
    }
    bridge.compile("embedded-mongodb-cxx");
    if let Some(directory) = static_libstdcxx {
        // Emitted after compile(), so the archive that needs these symbols precedes them on
        // the link line.
        println!("cargo:rustc-link-search=native={}", directory.display());
        println!("cargo:rustc-link-lib=static=stdc++");
    }

    // Keep the OUT_DIR indirection rather than pointing the link search at the cache: cargo
    // only adds a build script's -L directories to the platform's dylib search path when
    // they sit under the target directory, so linking straight from the cache would keep the
    // wheel working while breaking every `cargo test`, example and bench.
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib=dylib=embedded_mongodb_native");
}

/// `EMBEDDED_MONGODB_NATIVE_LIB_DIR` > `EMBEDDED_MONGODB_BUILD_FROM_SOURCE` > prebuilt.
fn resolve(workspace_root: &Path, crate_root: &Path, target: &str) -> PathBuf {
    if let Some(native_dir) = env::var_os("EMBEDDED_MONGODB_NATIVE_LIB_DIR") {
        let native_dir = PathBuf::from(native_dir);
        // Watch the directory, not the file inside it: a `rerun-if-changed` on a path that
        // does not exist marks this script permanently dirty and re-runs it on every build.
        println!("cargo:rerun-if-changed={}", native_dir.display());
        // This outranks both the manifest and a source build, with no checksum and no
        // freshness check, so a stale value left in a shell profile or a Dockerfile would
        // otherwise shadow everything silently.
        println!(
            "cargo:warning=embedded-mongodb: using the native library in \
             EMBEDDED_MONGODB_NATIVE_LIB_DIR={}, not the published one",
            native_dir.display()
        );
        return native_dir.join(NATIVE_LIBRARY);
    }

    if flag("EMBEDDED_MONGODB_BUILD_FROM_SOURCE") {
        // Watched only here. Once downloading is the default most checkouts have no
        // submodule at all, and a watch on a missing path re-runs this script every time.
        println!(
            "cargo:rerun-if-changed={}",
            workspace_root.join("mongo/.bazelversion").display()
        );
        println!(
            "cargo:rerun-if-changed={}",
            workspace_root.join("mongo/.bazelrc").display()
        );
        return build_native(workspace_root, crate_root);
    }

    let Some(entry) = PREBUILT.iter().find(|entry| entry.target == target) else {
        // Never fall back to bazel here: an unannounced multi-hour, ~9 GB build is far worse
        // than one line naming the variable that starts one deliberately.
        let published: Vec<&str> = PREBUILT.iter().map(|entry| entry.target).collect();
        let available = if published.is_empty() {
            "no prebuilt libraries have been published yet".to_string()
        } else {
            format!("release {RELEASE_TAG} has: {}", published.join(", "))
        };
        panic!(
            "no prebuilt embedded MongoDB library is published for `{target}` ({available}).\
             \n\n  \
             * build the engine yourself: EMBEDDED_MONGODB_BUILD_FROM_SOURCE=1 cargo build\n  \
             * or supply one you have:    EMBEDDED_MONGODB_NATIVE_LIB_DIR=<dir containing \
             {NATIVE_LIBRARY}>\n"
        );
    };
    check_not_stale(workspace_root);
    check_glibc_floor(entry);
    fetch_prebuilt(entry)
}

/// Hard-errors when this checkout's native inputs no longer match the published library.
///
/// Every question runs from the workspace root: a build script's working directory is the
/// package directory, and a pathspec naming `mongo` from inside `embedded-mongodb-sys`
/// matches nothing and exits 0, which would silently drop the engine pin from the
/// comparison. Fails open only where the question is genuinely unanswerable -- no git, a
/// shallow clone, a vendored tarball -- and always says so.
fn check_not_stale(workspace_root: &Path) {
    let git = |args: &[&str]| -> Option<String> {
        let output = Command::new("git")
            .args(args)
            .current_dir(workspace_root)
            .output()
            .ok()?;
        output
            .status
            .success()
            .then(|| String::from_utf8_lossy(&output.stdout).trim().to_string())
    };

    let Some(published_pin) = git(&["rev-parse", &format!("{SOURCE_COMMIT}^{{commit}}:mongo")])
    else {
        println!(
            "cargo:warning=embedded-mongodb: cannot check that the prebuilt library matches \
             this checkout, because commit {SOURCE_COMMIT} is not in this repository. \
             Using {RELEASE_TAG} anyway."
        );
        return;
    };

    // Read the submodule's own HEAD when it is checked out. The recorded gitlink does not
    // move on a local `cd mongo && git checkout <other-sha>`, so comparing gitlinks alone
    // would miss exactly the developer testing another engine revision.
    let local_pin = if workspace_root.join("mongo/.git").exists() {
        git(&["-C", "mongo", "rev-parse", "HEAD"])
    } else {
        git(&["rev-parse", "HEAD:mongo"])
    };

    let mut reasons = Vec::new();
    if let Some(local_pin) = local_pin
        && local_pin != published_pin
    {
        reasons.push(format!(
            "the mongo submodule is at {local_pin}, the prebuilt was built from {published_pin}"
        ));
    }

    let range = format!("{SOURCE_COMMIT}..HEAD");
    let mut args = vec!["rev-list", "--count", &range, "--"];
    args.extend_from_slice(ARTIFACT_PATHS);
    args.push("mongo");
    if let Some(count) = git(&args)
        && count != "0"
    {
        reasons.push(format!(
            "{count} commit(s) since {SOURCE_COMMIT} changed the native inputs"
        ));
    }

    let mut args = vec!["status", "--porcelain", "--"];
    args.extend_from_slice(ARTIFACT_PATHS);
    args.push("mongo");
    if let Some(dirty) = git(&args)
        && !dirty.is_empty()
    {
        reasons.push(format!(
            "uncommitted changes:\n    {}",
            dirty.replace('\n', "\n    ")
        ));
    }

    if reasons.is_empty() {
        return;
    }
    panic!(
        "the native library inputs in this checkout no longer match the published library \
         ({RELEASE_TAG}, built from {SOURCE_COMMIT}).\n\n  {}\n\n\
         Choose one:\n  \
         * build the engine yourself:     EMBEDDED_MONGODB_BUILD_FROM_SOURCE=1 cargo build\n  \
         * publish a build for this tree: gh workflow run native.yml --ref <this branch>\n  \
         * point at a library you have:   EMBEDDED_MONGODB_NATIVE_LIB_DIR=<dir>\n",
        reasons.join("\n  ")
    );
}

/// The published Linux library's glibc floor is whatever the machine that built it had.
/// Without this check the build succeeds and the failure lands at load time as
/// `version 'GLIBC_2.39' not found`, which says nothing about where the library came from.
fn check_glibc_floor(entry: &Prebuilt) {
    let Some((need_major, need_minor)) = entry.glibc_min else {
        return;
    };
    let Some((have_major, have_minor)) = host_glibc() else {
        println!(
            "cargo:warning=embedded-mongodb: could not read this host's glibc version; the \
             prebuilt library needs {need_major}.{need_minor} or newer"
        );
        return;
    };
    if (have_major, have_minor) >= (need_major, need_minor) {
        return;
    }
    panic!(
        "the prebuilt embedded MongoDB library for `{}` needs glibc {need_major}.{need_minor} \
         or newer, but this host has {have_major}.{have_minor}.\n\n  \
         * build the engine yourself: EMBEDDED_MONGODB_BUILD_FROM_SOURCE=1 cargo build\n  \
         * or supply one built for this host with EMBEDDED_MONGODB_NATIVE_LIB_DIR\n",
        entry.target
    );
}

fn host_glibc() -> Option<(u32, u32)> {
    let parse = |text: &str| -> Option<(u32, u32)> {
        // "glibc 2.44", or ldd's "ldd (GNU libc) 2.44".
        let version = text.split_whitespace().last()?;
        let mut parts = version.split('.');
        Some((parts.next()?.parse().ok()?, parts.next()?.parse().ok()?))
    };
    if let Ok(output) = Command::new("getconf").arg("GNU_LIBC_VERSION").output()
        && output.status.success()
        && let Some(version) = parse(String::from_utf8_lossy(&output.stdout).trim())
    {
        return Some(version);
    }
    let output = Command::new("ldd").arg("--version").output().ok()?;
    parse(String::from_utf8_lossy(&output.stdout).lines().next()?)
}

/// Returns a cached, checksum-verified copy of the published library, downloading it first
/// if it is not already there.
fn fetch_prebuilt(entry: &Prebuilt) -> PathBuf {
    // Flat and content-addressed, so two builds wanting the same bytes converge on one path
    // and a manifest bump can never collide with the entry it replaces. Not under the target
    // directory: `cargo clean` must not discard a 33 MB download.
    let cache = cache_dir();
    let destination = cache.join(format!("{}.so", entry.sha256));
    println!("cargo:rerun-if-changed={}", destination.display());
    match verify(&destination, entry) {
        None => return destination,
        Some(Problem::Missing) => {}
        // Truncated by a full disk, or otherwise corrupted. Drop it and fetch again.
        Some(_) => {
            let _ = fs::remove_file(&destination);
        }
    }

    let url = format!("{BASE_URL}/{RELEASE_TAG}/{}", entry.asset);
    if flag("CARGO_NET_OFFLINE") {
        panic!(
            "the prebuilt embedded MongoDB library for `{}` is not in the local cache and \
             CARGO_NET_OFFLINE is set.\n\n  \
             expected at:    {}\n  would download: {url}\n\n  \
             * seed the cache on a networked machine, or point \
             EMBEDDED_MONGODB_NATIVE_LIB_DIR at a directory holding {NATIVE_LIBRARY}\n  \
             * or build the engine yourself: EMBEDDED_MONGODB_BUILD_FROM_SOURCE=1\n",
            entry.target,
            destination.display()
        );
    }

    fs::create_dir_all(&cache)
        .unwrap_or_else(|error| panic!("failed to create {}: {error}", cache.display()));
    sweep_stale_temporaries(&cache);

    // `cargo build --offline` does not export CARGO_NET_OFFLINE to build scripts, so the
    // flag form cannot be detected here. Say what is about to happen rather than reaching
    // the network silently.
    println!("cargo:warning=embedded-mongodb: downloading the prebuilt engine from {url}");

    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|elapsed| elapsed.subsec_nanos())
        .unwrap_or_default();
    // In the destination directory, so the rename below is same-filesystem and atomic. No
    // lock file: the worst case for two cold builds racing is one duplicated download.
    let temporary = cache.join(format!(".tmp-{}-{nanos}", std::process::id()));
    if let Err(error) = fetch(&url, &temporary) {
        let _ = fs::remove_file(&temporary);
        panic!(
            "failed to download the prebuilt embedded MongoDB library: {error}\n  url: {url}\n\n  \
             * build the engine yourself: EMBEDDED_MONGODB_BUILD_FROM_SOURCE=1 cargo build\n  \
             * or supply one you have:    EMBEDDED_MONGODB_NATIVE_LIB_DIR=<dir>\n"
        );
    }

    // The two failures get different messages on purpose. curl does not retry a mid-transfer
    // break, so a truncated download is the common one and must not wear the alarming text.
    match verify(&temporary, entry) {
        None => {}
        Some(Problem::Missing) => panic!("{} vanished after download", temporary.display()),
        Some(Problem::Size { actual }) => {
            let _ = fs::remove_file(&temporary);
            panic!(
                "the download was truncated: got {actual} of {} bytes from {url}.\n  \
                 re-run the build to retry.\n",
                entry.size
            );
        }
        Some(Problem::Digest { actual }) => {
            let _ = fs::remove_file(&temporary);
            panic!(
                "checksum mismatch for the prebuilt embedded MongoDB library.\n  url:      \
                 {url}\n  expected: {}\n  actual:   {actual}\n\n  \
                 The file is the expected size but not the expected bytes, so the release \
                 asset may have been replaced. It has not been used.\n",
                entry.sha256
            );
        }
    }

    if fs::rename(&temporary, &destination).is_err() {
        // A racing build may have installed identical bytes already, and an entry that
        // verifies is the entry we wanted either way.
        let installed = verify(&destination, entry).is_none();
        let _ = fs::remove_file(&temporary);
        assert!(installed, "failed to install {}", destination.display());
    }
    destination
}

/// On macOS, take ownership of the copy in `OUT_DIR`. ld64 copies `LC_ID_DYLIB` verbatim
/// into every consumer's `LC_LOAD_DYLIB`, so rewriting it to this absolute path is what lets
/// standalone binaries, `cargo test` and maturin's Mach-O repair all resolve it without rpath
/// plumbing in other crates -- which matters, because `cargo:rustc-link-arg` does not reach
/// a crate's dependents. Elsewhere a symlink is enough: the ELF carries no `DT_SONAME`, so
/// consumers record the bare file name and find it through the search path cargo exports.
fn install(source: &Path, destination: &Path, target_os: &str, host: &str) {
    match fs::remove_file(destination) {
        Ok(()) => {}
        Err(error) if error.kind() == ErrorKind::NotFound => {}
        Err(error) => panic!("failed to replace {}: {error}", destination.display()),
    }

    if target_os != "macos" {
        #[cfg(unix)]
        std::os::unix::fs::symlink(source, destination)
            .expect("failed to link the native library into OUT_DIR");
        #[cfg(not(unix))]
        fs::copy(source, destination).expect("failed to copy the native library into OUT_DIR");
        return;
    }

    // install_name_tool and codesign are host tools.
    assert!(
        host.contains("apple-darwin"),
        "cross-compiling to {target_os} from {host} needs install_name_tool and codesign, \
         which only exist on macOS. Build on a macOS host, or supply a finished library with \
         EMBEDDED_MONGODB_NATIVE_LIB_DIR."
    );
    fs::copy(source, destination)
        .unwrap_or_else(|error| panic!("failed to copy into {}: {error}", destination.display()));
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        // Bazel outputs are mode 0555 and fs::copy preserves that, which would stop the next
        // build from replacing this file.
        let _ = fs::set_permissions(destination, fs::Permissions::from_mode(0o755));
    }
    let id = destination.to_str().expect("OUT_DIR must be valid UTF-8");
    run("install_name_tool", &["-id", id, id]);
    // install_name_tool invalidates the linker's ad-hoc signature without replacing it, and
    // an unsigned arm64 dylib is killed at load time.
    run("codesign", &["--force", "--sign", "-", id]);
}

fn run(program: &str, args: &[&str]) {
    let status = Command::new(program)
        .args(args)
        .status()
        .unwrap_or_else(|error| panic!("failed to run {program}: {error}"));
    assert!(status.success(), "{program} failed with {status}");
}

/// curl first, wget only as a fallback for images that ship one and not the other. No new
/// crates, and curl uses the system trust store, which a TLS-inspecting proxy needs.
fn fetch(url: &str, destination: &Path) -> Result<(), String> {
    let mut last = String::from("neither curl nor wget is installed");
    for name in ["curl", "wget"] {
        let mut command = Command::new(name);
        if name == "wget" {
            command.args(["--quiet", "--timeout=60", "--tries=3", "--output-document"]);
        } else {
            command.args([
                "--silent",
                "--show-error",
                "--location",
                "--fail",
                // Refuses a redirect down to plain http.
                "--proto",
                "=https",
                "--tlsv1.2",
                "--retry",
                "3",
                "--retry-connrefused",
                "--connect-timeout",
                "30",
                "--max-time",
                "1800",
                "--output",
            ]);
        }
        command.arg(destination).arg(url);
        match command.status() {
            Ok(status) if status.success() => return Ok(()),
            // It ran and failed -- 404, TLS, proxy. Report that rather than hiding it behind
            // the next downloader's error.
            Ok(status) => return Err(format!("{name} exited with {status}")),
            Err(error) if error.kind() == ErrorKind::NotFound => {
                last = format!("{name} is not installed");
            }
            Err(error) => return Err(format!("failed to run {name}: {error}")),
        }
    }
    Err(last)
}

enum Problem {
    Missing,
    Size { actual: u64 },
    Digest { actual: String },
}

/// Size first: it is a free `stat`, and it is what separates "truncated, retry" from "wrong
/// bytes, do not use". Runs on every build-script invocation rather than only after a
/// download, so a cache entry a full disk truncated is caught too.
fn verify(path: &Path, entry: &Prebuilt) -> Option<Problem> {
    let Ok(metadata) = fs::metadata(path) else {
        return Some(Problem::Missing);
    };
    if !metadata.is_file() {
        return Some(Problem::Missing);
    }
    if metadata.len() != entry.size {
        return Some(Problem::Size {
            actual: metadata.len(),
        });
    }
    match sha256(path) {
        Ok(digest) if digest == entry.sha256 => None,
        Ok(digest) => Some(Problem::Digest { actual: digest }),
        Err(_) => Some(Problem::Missing),
    }
}

fn sha256(path: &Path) -> std::io::Result<String> {
    let mut file = fs::File::open(path)?;
    let mut hasher = Sha256::new();
    let mut buffer = vec![0u8; 64 * 1024];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect())
}

/// A build killed mid-download leaks a 33 MB temporary permanently; nothing else removes it.
fn sweep_stale_temporaries(cache: &Path) {
    let Ok(entries) = fs::read_dir(cache) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let temporary = path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.starts_with(".tmp-"));
        if !temporary {
            continue;
        }
        let stale = entry
            .metadata()
            .ok()
            .and_then(|metadata| metadata.modified().ok())
            .and_then(|modified| SystemTime::now().duration_since(modified).ok())
            .is_some_and(|age| age > Duration::from_secs(24 * 60 * 60));
        if stale {
            let _ = fs::remove_file(&path);
        }
    }
}

fn cache_dir() -> PathBuf {
    if let Some(dir) = env::var_os("EMBEDDED_MONGODB_CACHE_DIR") {
        return PathBuf::from(dir);
    }
    if let Some(dir) = env::var_os("XDG_CACHE_HOME") {
        return PathBuf::from(dir).join("embedded-mongodb");
    }
    if let Some(home) = env::var_os("HOME") {
        let home = PathBuf::from(home);
        return if cfg!(target_os = "macos") {
            home.join("Library/Caches/embedded-mongodb")
        } else {
            home.join(".cache/embedded-mongodb")
        };
    }
    // Correct, just not shared between target directories.
    PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("cache")
}

/// Directory holding `libstdc++.a`, or `None` when the toolchain ships no static C++
/// runtime. `rustc` searches its own link paths rather than the compiler's internal library
/// directory, so the location has to be handed to it explicitly. Distributions differ on
/// where it lives -- and some ship only the shared library -- so ask the compiler.
fn static_libstdcxx_dir() -> Option<PathBuf> {
    let compiler = env::var("CXX").unwrap_or_else(|_| "c++".into());
    let output = Command::new(compiler)
        .arg("-print-file-name=libstdc++.a")
        .output()
        .ok()?;
    // A compiler that cannot find the file echoes the bare name back.
    let path = PathBuf::from(String::from_utf8_lossy(&output.stdout).trim());
    if !output.status.success() || !path.is_file() {
        println!(
            "cargo:warning=embedded-mongodb: no static libstdc++ found; linking it \
             dynamically, which ties this build to the host's GLIBCXX version"
        );
        return None;
    }
    Some(path.parent()?.to_path_buf())
}

/// True for `1`, `true`, `yes` -- anything but empty, `0` and `false`.
fn flag(name: &str) -> bool {
    env::var(name).is_ok_and(|value| {
        let value = value.trim();
        !value.is_empty() && value != "0" && !value.eq_ignore_ascii_case("false")
    })
}
