//! Finds the native MongoDB engine and links it in.
//!
//! By default it downloads the library published for this target and verifies its checksum;
//! building the engine from the pinned submodule takes hours, so it happens only when asked
//! for. Nothing in this file decides what the library *contains* -- that is `build_native`,
//! which is deliberately separate so a fix to the downloader does not invalidate every
//! library already published.
//!
//! The rest is split the same way, by what a change to it would invalidate: `build_freshness`
//! and `build_exports` decide whether a published library may be used here at all,
//! `build_download` and `build_cache` get its bytes onto the machine, `build_glibc` decides
//! whether they will load, and `build_link` hands them to the linker.

use std::env;
use std::path::{Path, PathBuf};

// Everything that decides what the native library contains.
mod build_android;
mod build_native;

mod build_cache;
mod build_download;
mod build_exports;
mod build_freshness;
mod build_glibc;
mod build_link;
mod build_logging;

// @generated by scripts/write-prebuilt-manifest. The one file here still pulled in
// textually: it is written by a shell script that reproduces this exact shape, and its
// constants have to reach every module above, which private items in the crate root do and
// private items in a sibling module do not. Nothing in it is written by hand, so the rustfmt
// coverage a module would buy would cover nothing.
include!("prebuilt.rs");

const NATIVE_LIBRARY: &str = "libembedded_mongodb_native.so";

/// Paths whose contents decide what the published library contains, relative to the
/// workspace root. `mongo` is the submodule gitlink: `git rev-list` reports a gitlink move as
/// a change to this path, which is why no content hash is needed.
const ARTIFACT_PATHS: &[&str] = &[
    "patches",
    "embedded-mongodb-sys/native",
    "embedded-mongodb-sys/build_native.rs",
    "embedded-mongodb-sys/build_android.rs",
];

/// One published artifact. The asset name is recorded rather than derived, so that CI writes
/// down exactly what it uploaded and the name and the hash cannot drift apart.
struct Prebuilt {
    target: &'static str,
    asset: &'static str,
    sha256: &'static str,
    size: u64,
    /// Minimum host glibc, for `*-linux-gnu` targets. `None` elsewhere.
    glibc_min: Option<(u32, u32)>,
}

fn main() {
    let crate_root = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR for build scripts"),
    );
    let workspace_root = crate_root
        .parent()
        .expect("embedded-mongodb-sys must be inside the workspace")
        .to_path_buf();
    let target = env::var("TARGET").expect("cargo sets TARGET for build scripts");
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let host = env::var("HOST").unwrap_or_default();

    for name in [
        "EMBEDDED_MONGODB_NATIVE_LIB_DIR",
        "EMBEDDED_MONGODB_BUILD_FROM_SOURCE",
        "EMBEDDED_MONGODB_CACHE_DIR",
        "EMBEDDED_MONGODB_BAZEL_JOBS",
        "EMBEDDED_MONGODB_ANDROID_API",
        "CARGO_NET_OFFLINE",
        "BAZEL",
        "CC",
        "CXX",
        "ANDROID_NDK_HOME",
        "ANDROID_NDK_ROOT",
        "ANDROID_NDK",
    ] {
        println!("cargo:rerun-if-env-changed={name}");
    }

    // Watched on every resolution path, and as directories: a per-file list misses a newly
    // added patch or header. Without these the staleness check is unreachable for the two
    // edits developers actually make, and the next unrelated rebuild would compile
    // cpp/bridge.cc against a new native/embedded_mongodb_native.h while linking the engine
    // built from the old one. The six extern "C" names would still match.
    println!("cargo:rerun-if-changed=native");
    println!("cargo:rerun-if-changed=include");
    println!("cargo:rerun-if-changed=src/ffi.rs");
    println!("cargo:rerun-if-changed=cpp/bridge.cc");
    // Only these three of this script's own files, and only because they are what the
    // staleness check compares: every module here is compiled into the script, so editing
    // one already relinks it and cargo re-runs it for that reason alone.
    println!("cargo:rerun-if-changed=prebuilt.rs");
    println!("cargo:rerun-if-changed=build_native.rs");
    println!("cargo:rerun-if-changed=build_android.rs");
    let patches = workspace_root.join("patches");
    if patches.is_dir() {
        println!("cargo:rerun-if-changed={}", patches.display());
    }

    let native_library = resolve(&workspace_root, &crate_root, &target);
    assert!(
        native_library.is_file(),
        "native library not found at {}",
        native_library.display()
    );
    let native_library = native_library
        .canonicalize()
        .expect("failed to resolve native library path");
    // After every resolution path rather than inside one of them: a library named by
    // EMBEDDED_MONGODB_NATIVE_LIB_DIR gets no checksum and no commit comparison, and a
    // freshly built one is only as current as the tree it came from.
    build_exports::check_exports(&native_library, &crate_root);

    let out_dir =
        PathBuf::from(env::var_os("OUT_DIR").expect("cargo sets OUT_DIR for build scripts"));
    build_link::install(
        &native_library,
        &out_dir.join(NATIVE_LIBRARY),
        &target_os,
        &host,
    );

    // Half of the C++ runtime story; the native library covers the other half through its
    // own link flags. Without this the cxx bridge puts a `NEEDED libstdc++.so.6` on every
    // artifact that links it -- the Python extension module included -- which pins the
    // wheel's GLIBCXX floor to whichever toolchain happened to build it.
    let static_libstdcxx = (target_os == "linux"
        && env::var("CARGO_CFG_TARGET_ENV").as_deref() == Ok("gnu"))
    .then(build_link::static_libstdcxx_dir)
    .flatten();
    let mut bridge = cxx_build::bridge("src/ffi.rs");
    bridge
        .file("cpp/bridge.cc")
        .include("include")
        .include("native")
        .std("c++20");
    if static_libstdcxx.is_some() {
        bridge.cpp_link_stdlib(None);
    }
    bridge.compile("embedded-mongodb-cxx");
    if let Some(directory) = static_libstdcxx {
        // Emitted after compile(), so the archive that needs these symbols precedes them on
        // the link line.
        println!("cargo:rustc-link-search=native={}", directory.display());
        println!("cargo:rustc-link-lib=static=stdc++");
    }

    // Keep the OUT_DIR indirection rather than pointing the link search at the cache: cargo
    // only adds a build script's -L directories to the platform's dylib search path when
    // they sit under the target directory, so linking straight from the cache would keep the
    // wheel working while breaking every `cargo test`, example and bench.
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib=dylib=embedded_mongodb_native");
}

/// `EMBEDDED_MONGODB_NATIVE_LIB_DIR` > `EMBEDDED_MONGODB_BUILD_FROM_SOURCE` > prebuilt.
fn resolve(workspace_root: &Path, crate_root: &Path, target: &str) -> PathBuf {
    if let Some(native_dir) = env::var_os("EMBEDDED_MONGODB_NATIVE_LIB_DIR") {
        let native_dir = PathBuf::from(native_dir);
        // Watch the directory, not the file inside it: a `rerun-if-changed` on a path that
        // does not exist marks this script permanently dirty and re-runs it on every build.
        println!("cargo:rerun-if-changed={}", native_dir.display());
        // This outranks both the manifest and a source build, with no checksum and no
        // freshness check, so a stale value left in a shell profile or a Dockerfile would
        // otherwise shadow everything silently.
        println!(
            "cargo:warning=embedded-mongodb: using the native library in \
             EMBEDDED_MONGODB_NATIVE_LIB_DIR={}, not the published one",
            native_dir.display()
        );
        return native_dir.join(NATIVE_LIBRARY);
    }

    if flag("EMBEDDED_MONGODB_BUILD_FROM_SOURCE") {
        // Watched only here. Once downloading is the default most checkouts have no
        // submodule at all, and a watch on a missing path re-runs this script every time.
        println!(
            "cargo:rerun-if-changed={}",
            workspace_root.join("mongo/.bazelversion").display()
        );
        println!(
            "cargo:rerun-if-changed={}",
            workspace_root.join("mongo/.bazelrc").display()
        );
        return build_native::build_native(workspace_root, crate_root);
    }

    let Some(entry) = PREBUILT.iter().find(|entry| entry.target == target) else {
        // Never fall back to bazel here: an unannounced multi-hour, ~9 GB build is far worse
        // than one line naming the variable that starts one deliberately.
        let published: Vec<&str> = PREBUILT.iter().map(|entry| entry.target).collect();
        let available = if published.is_empty() {
            "no prebuilt libraries have been published yet".to_string()
        } else {
            format!("release {RELEASE_TAG} has: {}", published.join(", "))
        };
        panic!(
            "no prebuilt embedded MongoDB library is published for `{target}` ({available}).\
             \n\n  \
             * build the engine yourself: EMBEDDED_MONGODB_BUILD_FROM_SOURCE=1 cargo build\n  \
             * or supply one you have:    EMBEDDED_MONGODB_NATIVE_LIB_DIR=<dir containing \
             {NATIVE_LIBRARY}>\n"
        );
    };
    build_freshness::check_not_stale(workspace_root);
    build_glibc::check_glibc_floor(entry);
    build_download::fetch_prebuilt(entry)
}

/// True for `1`, `true`, `yes` -- anything but empty, `0` and `false`.
fn flag(name: &str) -> bool {
    env::var(name).is_ok_and(|value| {
        let value = value.trim();
        !value.is_empty() && value != "0" && !value.eq_ignore_ascii_case("false")
    })
}
