// @generated by scripts/write-prebuilt-manifest -- do not edit by hand.
//
// Which published native libraries this checkout is entitled to download, and the exact
// bytes each one must have. The expected digests come from git rather than from the network,
// so replacing a release asset cannot go unnoticed.
//
// Regenerate by running the `native` workflow, which builds the engine, publishes a release
// and commits the result back.

/// Release holding the assets below.
const RELEASE_TAG: &str = "native-87fb7df4b63e";
/// Repository commit CI built them from. `build.rs` compares this checkout's native inputs
/// against it and refuses to use a library that no longer matches.
const SOURCE_COMMIT: &str = "1b0e6d18d952f04a98b51ac1ccdd85f74aeb74a4";
const BASE_URL: &str = "https://github.com/jeroenvervaeke/embedded-mongo/releases/download";

static PREBUILT: &[Prebuilt] = &[
    Prebuilt {
        target: "aarch64-apple-darwin",
        asset: "libembedded_mongodb_native-aarch64-apple-darwin.so",
        sha256: "5b471d259956346804d8c4aa1c91d7a1c3f8e7d6d9ce6c5a722a364ac3f0c6bd",
        size: 72765856,
        glibc_min: None,
    },
    Prebuilt {
        target: "aarch64-linux-android",
        asset: "libembedded_mongodb_native-aarch64-linux-android.so",
        sha256: "0f105a93d991580c50456ee5df17fb011acbdd2764df2c72957401db18c16288",
        size: 48598760,
        glibc_min: None,
    },
    Prebuilt {
        target: "aarch64-unknown-linux-gnu",
        asset: "libembedded_mongodb_native-aarch64-unknown-linux-gnu.so",
        sha256: "bb005bebc27d4c9787702b89c8a154f769795592748998cb2b91f7a50ee29766",
        size: 37518872,
        glibc_min: Some((2, 38)),
    },
    Prebuilt {
        target: "x86_64-linux-android",
        asset: "libembedded_mongodb_native-x86_64-linux-android.so",
        sha256: "c5ca4a6ff27dbcdcbfb29b5e70b431f4cceb859f1ed73710c9f2dd84df193024",
        size: 48057704,
        glibc_min: None,
    },
    Prebuilt {
        target: "x86_64-unknown-linux-gnu",
        asset: "libembedded_mongodb_native-x86_64-unknown-linux-gnu.so",
        sha256: "11914ca1bfa15fdc0350eb246354f628fd5fb24e9aa74cfdbc3108e7704ec476",
        size: 34575480,
        glibc_min: Some((2, 38)),
    },
];
