// @generated by scripts/write-prebuilt-manifest -- do not edit by hand.
//
// Which published native libraries this checkout is entitled to download, and the exact
// bytes each one must have. The expected digests come from git rather than from the network,
// so replacing a release asset cannot go unnoticed.
//
// Regenerate by running the `native` workflow, which builds the engine, publishes a release
// and commits the result back.

/// Release holding the assets below.
const RELEASE_TAG: &str = "native-unpublished";
/// Repository commit CI built them from. `build.rs` compares this checkout's native inputs
/// against it and refuses to use a library that no longer matches.
const SOURCE_COMMIT: &str = "0000000000000000000000000000000000000000";
const BASE_URL: &str = "https://github.com/jeroenvervaeke/embedded-mongo/releases/download";

static PREBUILT: &[Prebuilt] = &[];
