/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * An open data directory. One per process: the engine keeps a single runtime, and opening a
 * second directory before the first is closed is refused with a message saying so.
 */
export declare class Engine {
  /**
   * Opens the directory, creating it if it does not exist. Also runs the one-time index
   * repair pass over a directory an older build damaged, which is a scan of every
   * collection in it -- the longest thing this package ever does.
   */
  static open(path: string): Promise<Engine>
  /**
   * [`Engine::open`] for a caller with no loop to await on: `new MongoClient(...)` is a
   * constructor in the driver's API, and the engine has to be up before it returns.
   */
  static openSync(path: string): Engine
  /**
   * Runs one OP_MSG and answers the reply. Commands from other connections run alongside
   * this one -- the read guard is shared -- and only [`Engine::close`] excludes them.
   */
  roundTrip(message: Buffer): Promise<RoundTrip>
  /**
   * Closes the engine, waiting for the commands other connections are still running. The
   * write guard is a temporary of the first statement, so the engine's own shutdown runs
   * with the lock released, and a command arriving meanwhile is told the engine is closed.
   */
  close(): Promise<void>
  /**
   * [`Engine::close`] for the one caller with no loop to await on: `new MongoClient(...)`
   * undoing its own open when the rest of the constructor fails. Leaving the engine open
   * there would cost the process its one runtime, and every later open would be refused.
   */
  closeSync(): void
}

/** One reply, alongside what the listener needs to frame it. */
export interface RoundTrip {
  requestId: number
  /** The request's flag: a driver that set it wants no reply written. */
  moreToCome: boolean
  /** The request was an OP_QUERY, so the reply has to be framed as an OP_REPLY. */
  legacy: boolean
  response: Buffer
}
